Necessary changes for on-prem deploys again
RoboJackets/apiary pull request #1357
Opened 2020-09-11 21:20 UTC by JoshOldenburg

Removes some of the changes made to support Vapor and reverts to requiring PHP 7.2.

2020-09-11 23:37 UTC, kberzinch requested changes
Please review the colo milestone and attach the appropriate tickets to this PR: https://github.com/RoboJackets/apiary/milestone/13

2020-09-11 23:37 UTC, kberzinch commented on app/Jobs/CreateOrUpdateUserFromBuzzAPI.php
> +        $this->queue = config('queue.name.buzzapi');
These should go back to being constants

2020-09-11 23:37 UTC, kberzinch commented on config/queue.php
> +    ],
Delete this

2020-09-11 23:37 UTC, kberzinch commented on phpcs.xml
> -        <exclude name="SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingNativeTypeHint"/>
You do want to keep this. Native property type hints are 7.4 only.

2020-10-01 04:18 UTC, JoshOldenburg commented
Fixes #1339, #1341, and #1342.

2020-10-01 14:44 UTC, JoshOldenburg commented
This is a diff from before the Vapor PR to this PR: https://github.com/RoboJackets/apiary/compare/fb8214...josh/onprem

I read through that diff and I don't see anything problematic.

2020-10-01 23:05 UTC, kberzinch approved these changes

2020-10-02 00:34 UTC, merged