Adding Graduation Date to Dues Flow
RoboJackets/apiary pull request #1885
Opened 2021-07-31 22:26 UTC by sastorer

Adds a Semester and Year field that are individually validated.

Graduation Info conditionally shows up depending on the status of "Restricted to Students" in the selected dues package.

2021-07-31 22:55 UTC, JoshOldenburg submitted a review, later dismissed
Looks good to me once CI passes.

2021-07-31 23:15 UTC, JoshOldenburg approved these changes

2021-07-31 23:22 UTC, kberzinch requested changes
Doesn't work in test

2021-08-01 00:42 UTC, kberzinch approved these changes

2021-08-01 00:44 UTC, JoshOldenburg approved these changes

2021-08-01 00:48 UTC, merged