Add new field to indicate if a merch item is distributable
RoboJackets/apiary pull request #3159
Opened 2022-12-15 05:12 UTC by evan10s

This will allow us to remove some logic determining distributability based on presence of the word "waive" in a merch item's name.

Also:
* Add details about `CAS_CLIENT_SERVICE` env var to README and .env.example
* Fixed a typo (displayble -> displayable) that was present in a bunch of Nova model files
* Added a jank workaround for a Nova bug causing the `provided_by` field to not be sent to the backend by the Distribute Merchandise action

Closes #3073

2022-12-17 02:08 UTC, JoshOldenburg requested changes

2022-12-17 02:08 UTC, JoshOldenburg commented on database/migrations/2022_12_14_231443_add_merchandise_distributable_field.php
> +            $table->boolean('distributable')->default(false);
```suggestion
            $table->boolean('distributable')->default(true);
```
Per Slack disucssion

2022-12-17 15:46 UTC, kberzinch approved these changes
lgtm other than note from josh

2022-12-17 21:43 UTC, kberzinch approved these changes

2022-12-18 17:02 UTC, JoshOldenburg approved these changes

2022-12-18 17:02 UTC, merged