Updated trip CRUD UX in Nova
RoboJackets/apiary pull request #4285
Opened 2024-01-15 23:07 UTC by kberzinch

- Nova trip CRUD UI mostly replaced (closes #2674, closes #4019)
- DocuSign toggles are now in a dedicated `forms` column on the trip instead of reusing `tar_required` and `tar_transportation_mode`
- Other code that relied on those columns has been updated appropriately
- "TAR Received" metric renamed to "Forms Received" (closes #3491)
- Project manager search on teams and primary contact search on trips is now filtered to `team-lead`s, `project-manager`s, and `officer`s only (closes #3557)

Partial progress towards #3488, #2618

2024-01-15 23:27 UTC, kberzinch commented on app/Nova/Travel.php
> +                    ->searchable()
This is I think just using basic substring search on the frontend. We can make this fuzzy search with a model like we did for airports but that feels like overkill.

2024-01-15 23:34 UTC, kberzinch commented on app/Nova/User.php
> +        if ($request->field === 'projectManager' || $request->field === 'primaryContact') {
This is going to be a little weird in test because the Meilisearch index is out of date. Lmk if I need to import things.

2024-02-03 15:50 UTC, JoshOldenburg requested changes
A few minor things but overall looks good. Not my most thorough review ever but at this point something is better than nothing.

2024-02-03 15:53 UTC, kberzinch commented on app/Nova/Travel.php
>                  ->rules('required', 'date', 'before:return_date'),
I'm inclined to leave it as-is for now, it works for all of the trips that are currently logged.

2024-02-03 15:56 UTC, kberzinch commented on app/Nova/Travel.php
> +            }
GTF is the legal entity but the accounts are held on behalf of specific departments. GTF250000211 is held on behalf of Mechanical Engineering, hence the 250 in the account number.

Again, this works for most trips, and if it becomes a problem we can revisit it.

2024-02-03 15:58 UTC, kberzinch commented on app/Nova/Travel.php
> -                ->help('This should typically be the name of the competition followed by the year.')
I think I was fiddling around with adding more guidance here but didn't end up doing that.

2024-02-03 16:07 UTC, kberzinch commented on app/Nova/Travel.php
> +                    ->help('If you are not staying overnight, leave this field blank.')
What other fields are per se optional?

2024-02-03 16:09 UTC, JoshOldenburg commented on app/Nova/Travel.php
> +                    ->help('If you are not staying overnight, leave this field blank.')
Never mind, I was looking at the costs but they say to enter 0 instead of leaving it blank.

2024-02-03 16:16 UTC, JoshOldenburg approved these changes

2024-02-05 00:57 UTC, evan10s approved these changes

2024-02-05 00:58 UTC, merged